import type {
  AIProvider,
  CaseStudyDraft,
  CaseStudySubject,
  DmSequence,
  DmSubject,
  PersonalisationSubject,
  PersonalisedEmail,
  ProspectCriteria,
  ResearchResult,
  ResearchSubject,
  SocialPostSet,
  SocialSubject,
  SocialVariation,
} from "../types";

/**
 * Offline adapter for development and tests.
 *
 * It is deliberately *derivational*, not random: every field is computed from
 * the real record in front of it, and the summary says plainly that it was
 * generated without a model. That keeps the feature end-to-end testable without
 * an API key while making it impossible to mistake the output for real
 * model-generated research.
 */
export class MockAIProvider implements AIProvider {
  readonly name = "mock";
  readonly model = "deterministic-rules";

  isConfigured(): boolean {
    return true;
  }

  async researchLead(subject: ResearchSubject): Promise<ResearchResult> {
    const size = subject.employeeCount ?? 0;
    const hasWebsite = Boolean(subject.websiteText);
    const hasContact = Boolean(subject.contactName && subject.jobTitle);
    const industry = subject.industry?.toLowerCase() ?? "";

    // Transparent, additive scoring so the reason always matches the number.
    const factors: { label: string; points: number }[] = [];
    if (size >= 10 && size <= 200)
      factors.push({ label: `headcount ${size} is in the sweet spot`, points: 25 });
    else if (size > 0)
      factors.push({ label: `headcount ${size} is outside the ideal band`, points: 8 });
    else factors.push({ label: "headcount unknown", points: 0 });

    if (subject.niche)
      factors.push({ label: `assigned to the ${subject.niche.name} niche`, points: 20 });
    if (hasContact)
      factors.push({ label: `a named decision maker (${subject.jobTitle}) is on file`, points: 18 });
    if (subject.contactEmail) factors.push({ label: "a direct email is available", points: 12 });
    if (hasWebsite) factors.push({ label: "the website was readable for research", points: 15 });
    if (subject.revenue && Number(subject.revenue) > 1_000_000)
      factors.push({ label: "reported revenue is above $1M", points: 10 });

    const score = Math.min(100, factors.reduce((sum, f) => sum + f.points, 0));

    return {
      summary:
        `${subject.companyName} is a ${subject.industry ?? "business"}` +
        `${subject.location ? ` based in ${subject.location}` : ""}` +
        `${size ? ` with roughly ${size} employees` : ""}. ` +
        `Generated by the offline mock provider from the stored record — set AI_PROVIDER=anthropic ` +
        `and ANTHROPIC_API_KEY for model-written research.`,
      whatTheyDo:
        subject.description ??
        `Operates in ${subject.industry ?? "an unspecified industry"}${
          subject.location ? ` serving the ${subject.location} market` : ""
        }.`,
      painPoints: derivePainPoints(industry, subject.niche?.painPoints ?? null),
      automationOpportunities: deriveOpportunities(industry),
      recommendedOffer:
        subject.niche?.offer ??
        "Automated lead capture, qualification and follow-up so no enquiry goes unanswered.",
      personalization: [
        subject.jobTitle
          ? `Address ${subject.contactName ?? "the contact"} as ${subject.jobTitle}.`
          : "No named contact yet — find the decision maker before outreach.",
        subject.location ? `Reference their ${subject.location} market.` : "Location unknown.",
        hasWebsite
          ? "Reference a specific service listed on their website."
          : "Website could not be read — review it manually before sending.",
      ],
      score,
      scoreReason: `${score}/100 — ${factors.map((f) => f.label).join("; ")}.`,
      // Confidence tracks how much real input existed, never a flat constant.
      confidence: Math.min(
        0.9,
        0.3 + (hasWebsite ? 0.3 : 0) + (hasContact ? 0.2 : 0) + (size ? 0.1 : 0),
      ),
    };
  }

  /**
   * Deterministic stand-in so the whole send pipeline can be exercised offline.
   * It composes the opener from the same fact sheet the real providers get, so
   * a preview built here is structurally identical to a live one.
   */
  async personaliseEmail(subject: PersonalisationSubject): Promise<PersonalisedEmail> {
    const s = subject.signals;
    const observations: string[] = [];
    if (s?.runsAds && s.adPlatforms?.length) {
      observations.push(`you're running ads (${s.adPlatforms.join(", ")})`);
    }
    if (s?.hasLiveChat === false) observations.push("there's no live chat on your site");
    if (s?.hasBooking === false) observations.push("bookings still go through the phone");
    if (s?.hasVideo === false) observations.push("there's no video on the site");

    const lead = observations[0] ?? `I came across ${subject.companyName}`;
    const second = observations[1];

    const body = [
      // Many of these contacts are role inboxes with no person behind them,
      // so an empty name must fall back rather than render "Hi ,".
      `Hi ${subject.contactName?.trim().split(/\s+/)[0] || "there"},`,
      "",
      `I had a look at ${subject.companyName} and noticed ${lead}${second ? `, and ${second}` : ""}.`,
      "",
      `I do ${subject.offer}. For a business your size that usually means fewer enquiries slipping through`,
      "the gaps, without adding headcount.",
      "",
      "Worth a short call?",
    ].join("\n");

    return {
      subject: `quick note about ${subject.companyName.toLowerCase()}`.slice(0, 60),
      body,
      basisUsed: observations.length ? observations : ["company name only"],
    };
  }

  /**
   * Same fact-sheet-derived structure as the real writers: observation →
   * problem → curiosity CTA, then a light callback follow-up. Template-shaped
   * on purpose, so nobody mistakes it for model-written copy.
   */
  async writeDmSequence(subject: DmSubject): Promise<DmSequence> {
    const s = subject.signals;
    const observations: string[] = [];
    if (s?.runsAds && s.adPlatforms?.length) {
      observations.push(`running ads (${s.adPlatforms.join(", ")})`);
    }
    if (s?.hasLiveChat === false) observations.push("no live chat on the site");
    if (s?.hasBooking === false) observations.push("no online booking on the site");
    if (s?.hasLeadForm === false) observations.push("no lead capture form on the site");
    if (s?.hasVideo === false) observations.push("no video on the site");

    const hook = observations[0]
      ? `Noticed ${subject.companyName} is ${observations[0]}`
      : `Came across ${subject.companyName} on ${subject.platform}`;
    const gap = observations[1] ?? observations[0] ?? "a gap worth a look";

    const where =
      subject.platform === "instagram" ? "IG"
      : subject.platform === "facebook" ? "Facebook"
      : subject.platform === "twitter" ? "X"
      : "LinkedIn";

    return {
      // Kept under 300 characters by construction — the note is unsendable otherwise.
      connectionNote:
        subject.platform === "linkedin"
          ? `${hook}. Building a few things around ${subject.offer.toLowerCase()} for similar businesses and thought it was worth connecting.`.slice(0, 300)
          : null,
      firstMessage:
        `${hook}. That usually means enquiries are slipping through without anyone seeing the cost. ` +
        `I put together a small fix around ${subject.offer.toLowerCase()} for cases exactly like this. ` +
        `Want me to send it over?`,
      secondMessage:
        `Think ${where} buried my last message. ` +
        `Still happy to show you the idea about ${gap}. Worth a look?`,
      basisUsed: observations.length ? observations : ["company name only"],
    };
  }

  /**
   * Derivational social copy for when no key is configured or the free-tier
   * quota is spent.
   *
   * It reuses the real project facts and the latest build log, and every
   * variation says plainly in its label that no model wrote it — the point is
   * a usable draft and an unmistakable one, never something that could be
   * pasted to a real audience by accident.
   */
  async writeSocialPosts(subject: SocialSubject): Promise<SocialPostSet> {
    const p = subject.project;
    const latest = subject.logs[0];
    const title = p?.title ?? subject.steer ?? "the current build";
    const stack = p?.stack.slice(0, 3).join(", ") || "the usual stack";
    const feature = p?.features[0] ?? "the first slice";
    const built = latest?.built ?? `working through ${feature}`;
    const blocker = latest?.blockers ?? null;
    const learned = latest?.learned ?? null;

    const tags =
      subject.platform === "twitter" || subject.platform === "contra"
        ? []
        : ["buildinpublic", "python", "fastapi"];

    const make = (label: string, hook: string, rest: string[]): SocialVariation => ({
      label: `${label} (offline draft — no model)`,
      hook,
      body: [hook, ...rest].join("\n\n"),
      cta: null,
      hashtags: tags,
    });

    const variations: SocialVariation[] = [
      make("Proof", `${built}.`, [`Part of ${title}. Built with ${stack}.`]),
      make(
        "Lesson",
        blocker ? `Spent longer than I want to admit on ${blocker}.` : `${feature} was harder than the plan made it look.`,
        [learned ? `What actually fixed it: ${learned}.` : `Still on ${title}, still ${stack}.`],
      ),
      make("Build log", `Day's work on ${title}: ${built}.`, [
        blocker ? `Still open: ${blocker}.` : `Next up: ${p?.features[1] ?? "the next slice"}.`,
      ]),
    ];

    return {
      angle: `${title}: ${built}`.slice(0, 80),
      premise: `Offline draft assembled from the project record and the most recent build log. No model was called.`,
      variations: variations.slice(0, subject.format === "showcase" ? 1 : 3),
      basisUsed: [
        p ? `project ${p.number}: ${p.title}` : "no project supplied",
        latest ? `build log ${latest.loggedOn}` : "no build logs",
      ],
    };
  }

  /**
   * Offline case study. Assembled from the record, and labelled as a draft in
   * the headline so it cannot be published by accident — this is the one piece
   * of copy on the site aimed at someone about to spend money.
   */
  async writeCaseStudy(subject: CaseStudySubject): Promise<CaseStudyDraft> {
    const p = subject.project;
    const latest = subject.logs[0];
    const stack = p.stack.join(", ") || "a standard web stack";

    return {
      headline: `[offline draft] ${p.title}`,
      intro: p.summary ?? `${p.title}, built with ${stack}.`,
      problem:
        "Written without a model, so this section needs replacing with the real problem this system addresses.",
      approach: latest
        ? `Built with ${stack}. Most recent work: ${latest.built}`
        : `Built with ${stack}.`,
      howItWorks: p.features.slice(0, 5),
      demonstrates: p.stack.slice(0, 4).map((tool) => `Working knowledge of ${tool}`),
      basisUsed: ["project record", latest ? `build log ${latest.loggedOn}` : "no build logs"],
    };
  }

  async parseProspectCriteria(prompt: string): Promise<ProspectCriteria> {
    const limitMatch = prompt.match(/\b(\d{1,4})\b/);
    const rangeMatch = prompt.match(
      /(\d{1,5})\s*(?:-|–|to)\s*(\d{1,5})\s*(?:employees|staff|people)/i,
    );

    return {
      description: prompt.trim(),
      niche: null,
      locations: extractLocations(prompt),
      minEmployees: rangeMatch ? Number(rangeMatch[1]) : null,
      maxEmployees: rangeMatch ? Number(rangeMatch[2]) : null,
      jobTitles: [],
      industries: [],
      limit: limitMatch ? Math.min(500, Math.max(1, Number(limitMatch[1]))) : 25,
    };
  }
}

const KNOWN_LOCATIONS = [
  "United States",
  "United Kingdom",
  "Canada",
  "Australia",
  "Germany",
  "Spain",
  "France",
  "Netherlands",
  "Ireland",
  "United Arab Emirates",
];

function extractLocations(prompt: string): string[] {
  const lower = ` ${prompt.toLowerCase()} `;
  const found = KNOWN_LOCATIONS.filter((l) => lower.includes(l.toLowerCase()));
  if (/\b(us|usa|u\.s\.)\b/.test(lower) && !found.includes("United States")) {
    found.push("United States");
  }
  if (/\buk\b/.test(lower) && !found.includes("United Kingdom")) {
    found.push("United Kingdom");
  }
  return found;
}

function derivePainPoints(industry: string, nichePainPoints: string | null): string[] {
  if (nichePainPoints) {
    return nichePainPoints
      .split(/[.;]\s*/)
      .map((p) => p.trim())
      .filter(Boolean)
      .slice(0, 4);
  }
  if (industry.includes("real estate"))
    return ["Inbound enquiries answered slowly", "No consistent nurture for cold leads"];
  if (industry.includes("dental") || industry.includes("health"))
    return ["Appointment no-shows", "Reception overloaded with inbound calls"];
  if (industry.includes("recruit") || industry.includes("staffing"))
    return ["Manual CV screening", "Candidates go cold between stages"];
  if (industry.includes("marketing") || industry.includes("advertis"))
    return ["Manual client reporting", "Slow client onboarding"];
  if (industry.includes("construction") || industry.includes("home"))
    return ["Missed calls become lost jobs", "Estimates never followed up"];
  return ["Manual repetitive admin", "Follow-up depends on someone remembering"];
}

function deriveOpportunities(industry: string): string[] {
  const base = [
    "Automated lead qualification and routing",
    "Scheduled multi-step follow-up sequences",
  ];
  if (industry.includes("dental") || industry.includes("health"))
    return ["Automated appointment reminders and recall", ...base];
  if (industry.includes("recruit")) return ["Automated CV screening and ranking", ...base];
  if (industry.includes("marketing")) return ["Automated client reporting", ...base];
  if (industry.includes("home") || industry.includes("construction"))
    return ["Missed-call capture with instant SMS response", ...base];
  return base;

}
